
"""PRE: se invoca la función inicio
POST:Muestra en pantalla la interfaz deseada"""
def inicio():
          print("   _           _   _   _           _     _")
          print("  | |         | | | | | |         | |   (_)")
          print("  | |__   __ _| |_| |_| | ___  ___| |__  _ _____")
          print("  | '_ \ / _` | __| __| |/ _ \/ __| '_ \| | '__ \ ")
          print("  | |_) | (_| | |_| |_| |  __/\__ \ | | | | |_) |")
          print("  |_.__/ \__,_|\__|\__|_|\___||___/_| |_|_| .__/ ")
          print("                                          | |")
          print("                                          |_)")

          print("")
          print("")

          print("                                      |\/")
          print("                                     ---")
          print("                                     / | [")
          print("                              !      | |||")
          print("                            _/|     _/|-++")
          print("                        +  +--|    |--|--|_ |-")
          print("                     { /|__|  |/\__|  |--- |||__/")
          print("                    +---------------___[}-_===_.____                 /\"")
          print("                ____`-' ||___-{]_| _[}-  |     |_[___\==--            \/   _")
          print(" __..._____--==/___]_|__|_____________________________[___\==--____,------' .7")
          print("|                                                                     BB-61/")
          print("\_________________________________________________________________________|)")

          print("")
          print("")
          print("Cargando juego Espere unos segundos......"+"\n"+"\n")
          for x in range(1,100000199):
                    y=1
                    x=y
          print("Bienvenido(a) a battleship, antes de empezar te diremos cuales son los tipos de barcos  que podras usar."+"\n"+"\n"+"Como Sabes tendras que acomodar un grupo de barcos tacticamente en un tablero, en este caso solo habran 5 barcos para acomodar , dos tipo A, dos tipo B y uno tipo C."+"\n"+"Es decir:")
          print("")
          print("Tipo A: Lanchas tacticas las cuales ocuparan solo una casilla."+"\n"+"Tipo b: Buques de guerra tan potentes que ocuparan tres casillas."+"\n"+"Tipo c: Portaaviones tan grandes que necesitan cuatro casillas.")
          print("")
          print("Se manejara un tablero 8x8, asi que piensa muy bien como ubicaras tus barcos para ganar.")
          print("Ya con eso es todo,Asi que ¡Empecemos!,por favor elige la dificultad")
          print("1: Classic"+"\n"+"2: Advanced")
          print("Escribe 1 o 2 dependiendo  de la dificultad que desees jugar:")
def explosion():
          print("           _,-~~/~    `---.")
          print("         _/_,---(      ,    )")
          print("     __ /        <    /   )  \___")
          print("- ------===;;;'====------------------===;;;===----- -  -")
          print("       \/  ~ ~ ~ ~ ~ ~\~ ~)~ /")
          print("       (_ (   \  (     >    \)")
          print("        \_( _ <         >_>'")
          print("           ~ `-i' ::>|--")
          print("               I;|.|.|")
          print("              <|i::|i|`.")
          print("               (` ^'`-' ")
def ini():
          print("       .---.")
          print("      /_____\"")
          print("      ( '.' )")
          print("       \_-_/_")
          print("    .-"'V'"//-.")
          print("   / ,   |// , \"")
          print("  / /|Ll //Ll|\ \"")
          print("  / /|__//   | \_\"")
          print("  \ /---|[]==| / /")
          print("  \/\__/ |   \/\/")
          print("   |/_   | Ll_\|")
          print("     |`^""^` |")
          print("     |   |   |")
          print("     |   |   |")
          print("     |   |   |")
          print("     |   |   |")
          print("     L___l___J")
          print("      |_ | _|")
          print("     (___|___)")
          print("      ^^^ ^^^")
def ini1():
          print("       .---.      SUERTE!!!!                      ")
          print("      /_____\"")
          print(" /\.-`( '.' )")
          print("/ /    \_-_/_")
          print("    .-"'V'"//-.")
          print(" `.__,   |// , \"")
          print("     |Ll //Ll|\ \"")
          print("     |__//   | \_\"")
          print("    /---|[]==| / /")
          print("    \__/ |   \/\/")
          print("    /_   | Ll_\|")
          print("     |`^""^` |")
          print("     |   |   |")
          print("     |   |   |")
          print("     |   |   |")
          print("     |   |   |")
          print("     L___l___J")
          print("      |_ | _|")
          print("     (___|___)")
          print("      ^^^ ^^^")

